org: groros
app: pay-per-lead-project
service: new-roofing-contractor-workflow
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
