org: groros
app: pay-per-lead-project
service: new-roofing-contractor-workflow
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  environment:
    REGION_NAME: ${self:provider.region}
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/906360379090/${self:service}-${self:provider.stage}-create-business-queue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:ListQueues
          Resource: arn:aws:sqs:us-east-1:906360379090:new-roofing-contractor-workflow-dev-create-business-queue 

functions:
  request_handler:
    handler: src/request_handler.request_handler
    events:
      - httpApi:
          path: /
          method: get
  create_business:
    handler: src/create_roofing_contractor.create_roofing_contractor
    events:
      - sqs: arn:aws:sqs:us-east-1:906360379090:new-roofing-contractor-workflow-dev-create-business-queue


constructs:
  create-business-queue:
    type: queue
    worker:
      handler: src/create_roofing_contractor.create_roofing_contractor

plugins:
  - serverless-lift
  - serverless-python-requirements
