org: groros
app: pay-per-lead-project
service: new-roofing-contractor-workflow
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  create_roofing_contractor:
    handler: src/create_roofing_contractor.create_roofing_contractor
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-lift
  - serverless-python-requirements
