org: groros
app: pay-per-lead-project
service: new-roofing-contractor-workflow
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  environment:
    REGION_NAME: ${self:provider.region}
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/906360379090/${self:service}-${self:provider.stage}-create-business-queue
    WORKFLOW_FILE: ${file(workflow.json.asl)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:ListQueues
          Resource: arn:aws:sqs:us-east-1:906360379090:new-roofing-contractor-workflow-dev-create-business-queue 

functions:
  request_handler:
    handler: src/request_handler.request_handler
    events:
      - httpApi:
          path: /
          method: post
  create_business:
    handler: src/create_roofing_contractor.create_roofing_contractor
    events:
      - sqs: arn:aws:sqs:us-east-1:906360379090:new-roofing-contractor-workflow-dev-create-business-queue
  has_stripe_customer:
    handler: src/check_if_stripe_customer_exists.check_if_stripe_customer_exists
    environment:
      STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
      STRIPE_API_KEY: ${param:STRIPE_API_KEY}
  create_stripe_customer:
    handler: src/create_stripe_customer.create_stripe_customer
    environment:
      STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
      STRIPE_API_KEY: ${param:STRIPE_API_KEY}
  add_stripe_customer_dynamo:
    handler: src/add_stripe_customer_dynamo.add_stripe_customer_dynamo
  send_slack_message:
    handler: src/send_slack_message.send_slack_message
  echo:
    handler: src/echo_handler.echo_handler


constructs:
  create-business-queue:
    type: queue
    worker:
      handler: src/create_roofing_contractor.create_roofing_contractor

plugins:
  - serverless-lift
  - serverless-python-requirements
  - serverless-step-functions

	
stepFunctions:
  stateMachines:
    createNewBusiness:
      name: create-business-workflow
      events:
        - http:
            path: create_roofer 
            method: POST
      definition: ${file(workflow.asl.yaml)}