name: Deploy master branch

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# name: Deploy Production
# # on main branch updates
# on:
#     push:
#         branches:
#             - main
# jobs:
#     deploy:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v1
#             - uses: actions/setup-node@v1
#               with:
#                   node-version: "12.x"
#               #install serverless
#             - name: Install Serverless Framework
#               run: npm install -g serverless
#               # authentication
#             - name: Serverless AWS authentication
#               run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY_DEPLOY }} --secret ${{ secrets.AWS_SECRET_DEPLOY }}
#               # create ENV, use the shell `cat` command to create env.yml from secrets
#             - name: Create env file
#               run: |
#                   cat > env.yml << EOF
#                   ${{ secrets.ENV }}
#                   EOF
#               #install node modules
#             - name: Install NPM dependencies
#               run: npm install
#               #serverless deploy
#             - name: Deploy
#               run: sls deploy -s prod
